### ISSUE TITLE
The plugin is not work

### ISSUE THREAD

**Issue by Hunlongyu** [dev5c32373043/parcel-reporter-clean-dist#1]
![image](https://user-images.githubusercontent.com/15273630/143851562-d74fbccc-1b34-439d-be56-81b4dd1348c0.png)

I have two entry files. When I build, It didn't delete the history files in dist

**Comment by dev5c32373043** [comment]
@Hunlongyu thank you for letting me know about this issue
I've updated the plugin with version 1.0.1 where the issue should be solved, so please update it for the latest version and try again. #2

**Comment by Hunlongyu** [comment]
It seems that the plugin is still not working.
![image](https://user-images.githubusercontent.com/15273630/144772524-2778c071-c905-4426-9ce4-3e589fee5af9.png)

1. Manually delete dist folder。
2. modify scss and build
3. modify scss and build agin
4. dist folder still have two css files
5. Then I added “cleanDistFiles” in package.json, it still not working

**Comment by dev5c32373043** [comment]
@Hunlongyu sorry this bug was replicable only on windows-based systems
I've updated the plugin to version 1.0.2 which contains a fix for this issue

**Comment by pieterdw** [comment]
@dev5c32373043 hi, I'm also trying out this plugin on Windows. Thanks for building this.
Unfortunately, it's still not working for me, even with version 1.0.2. So I played around a bit, and it seems like this line might be causing issues (getFilesToRemove.js, line 55):
`let filePath = path.posix.join(projectPath, itemToRemove);`
After this line, the filePath contains a combination of two paths in one string, something like "C:/MyProj/app1/C:/MyProj/dist/**/*"
I hope this helps with reproducing it. Just changing this line to this fixes it for me:
`let filePath = itemToRemove;`
Thank you!

**Comment by dev5c32373043** [comment]
@pieterdw thanks for letting me know, but unfortunately I can't replicate an issue that you described on windows 11(22000.348 build)
Can you provide more information like your os version, plugin configuration?

**Comment by pieterdw** [comment]
@dev5c32373043 I played around a bit more, and it looks like it's related to my monorepo setup.
I created a smaller project in which the issue can be reproduced: 
https://github.com/pieterdw/reproducing-parcel-reporter-clean-dist

The problem seems to be presenting itself here:
https://github.com/dev5c32373043/parcel-reporter-clean-dist/blob/29b32196ff74b381f840518682592fb2b8ede50b/src/getFilesToRemove.js#L48

The projectRoot path gets stripped from the distPath. But in my case the projectRoot is not inside the distPath:
- Project root: C:/Dev/Tests/reproducing-parcel-reporter-clean-dist/packages/example
- Dist path: C:/Dev/Tests/reproducing-parcel-reporter-clean-dist/dist

So the string doesn't change to a relative path, but keeps the full path instead. If you need any more info, just let me know. Thank you!

**Comment by dev5c32373043** [comment]
@pieterdw thanks for such a detailed example
I've updated the plugin to version 1.0.3 where your issue should be resolved, please check it when you have a chance

**Comment by pieterdw** [comment]
@dev5c32373043 awesome, I just tested it, and it looks like it's working. Thanks!

**Comment by dev5c32373043** [comment]
@pieterdw great, then I'll close this issue
